# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 20:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_type', models.CharField(choices=[('GR', 'Grassy'), ('MO', 'Mountain'), ('BU', 'Building'), ('SN', 'Snow'), ('WA', 'Water'), ('DE', 'Desert')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(802)])),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Climate')),
                ('evolves_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_from', to='pokedex.Pokemon')),
                ('evolves_into', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_into', to='pokedex.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_type', models.CharField(choices=[('KAN', 'Kanto'), ('JOH', 'Johto'), ('HOE', 'Hoenn'), ('SIN', 'Sinnoh'), ('UNO', 'Unova'), ('KAL', 'Kalos')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('attack', models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('defense', models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('special_attack', models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('special_defense', models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type', models.CharField(choices=[('NOR', 'Normal'), ('FIG', 'Fighting'), ('FLY', 'Flying'), ('POI', 'Poison'), ('GRO', 'Ground'), ('ROC', 'Rock'), ('BUG', 'Bug'), ('GHO', 'Ghost'), ('FIR', 'Fire'), ('WAT', 'Water'), ('GRA', 'Grass'), ('ELE', 'Electric'), ('PSY', 'Psychic'), ('ICE', 'Ice'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('STE', 'Steel'), ('FAI', 'Fairy')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Region'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Stats'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Trainer'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Type'),
        ),
    ]
