# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20170504_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_type',
        ),
        migrations.AddField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
