# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20170504_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='stats',
        ),
        migrations.AddField(
            model_name='stats',
            name='pokemon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Pokemon'),
        ),
    ]
