# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_auto_20170504_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_from', to='pokedex.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_into', to='pokedex.Pokemon'),
        ),
    ]
