# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_auto_20170504_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Pokemon')),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Pokemon_List'),
        ),
        migrations.AddField(
            model_name='pokemon_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Trainer'),
        ),
    ]
