# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_auto_20170504_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pokemon',
        ),
    ]
