# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 01:38
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0014_auto_20170504_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='pokemon_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NORMAL', 'Normal'), ('FIGHTING', 'Fighting'), ('FLYING', 'Flying'), ('POISON', 'Poison'), ('GROUND', 'Ground'), ('ROCK', 'Rock'), ('BUG', 'Bug'), ('GHOST', 'Ghost'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('GRASS', 'Grass'), ('ELECTRIC', 'Electric'), ('PSYCHIC', 'Psychic'), ('ICE', 'Ice'), ('DRAGON', 'Dragon'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=113),
        ),
        migrations.AlterField(
            model_name='type',
            name='strength',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NORMAL', 'Normal'), ('FIGHTING', 'Fighting'), ('FLYING', 'Flying'), ('POISON', 'Poison'), ('GROUND', 'Ground'), ('ROCK', 'Rock'), ('BUG', 'Bug'), ('GHOST', 'Ghost'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('GRASS', 'Grass'), ('ELECTRIC', 'Electric'), ('PSYCHIC', 'Psychic'), ('ICE', 'Ice'), ('DRAGON', 'Dragon'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=113, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='weakness',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NORMAL', 'Normal'), ('FIGHTING', 'Fighting'), ('FLYING', 'Flying'), ('POISON', 'Poison'), ('GROUND', 'Ground'), ('ROCK', 'Rock'), ('BUG', 'Bug'), ('GHOST', 'Ghost'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('GRASS', 'Grass'), ('ELECTRIC', 'Electric'), ('PSYCHIC', 'Psychic'), ('ICE', 'Ice'), ('DRAGON', 'Dragon'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=113, null=True),
        ),
    ]
