# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0016_auto_20170504_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='statistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Stats'),
        ),
    ]
