# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0018_auto_20170505_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprite',
            field=models.ImageField(upload_to=''),
        ),
    ]
